// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20241105220339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Model.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatedPost")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PostID");

                    b.HasIndex("UserID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostID = 1,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(972),
                            State = 0,
                            Title = "interduction1",
                            UserID = 1
                        },
                        new
                        {
                            PostID = 2,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(977),
                            State = 0,
                            Title = "interduction1",
                            UserID = 1
                        },
                        new
                        {
                            PostID = 3,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(983),
                            State = 0,
                            Title = "interductionTwo",
                            UserID = 2
                        },
                        new
                        {
                            PostID = 4,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(988),
                            State = 0,
                            Title = "interductionTwo",
                            UserID = 2
                        },
                        new
                        {
                            PostID = 5,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(993),
                            State = 0,
                            Title = "interductionThree",
                            UserID = 3
                        },
                        new
                        {
                            PostID = 6,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(998),
                            State = 0,
                            Title = "interductionFor",
                            UserID = 4
                        },
                        new
                        {
                            PostID = 7,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(1003),
                            State = 0,
                            Title = "interductionFive",
                            UserID = 5
                        },
                        new
                        {
                            PostID = 8,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(1007),
                            State = 0,
                            Title = "interductionSix",
                            UserID = 6
                        },
                        new
                        {
                            PostID = 9,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(1012),
                            State = 0,
                            Title = "interductionSix",
                            UserID = 6
                        },
                        new
                        {
                            PostID = 10,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(1017),
                            State = 0,
                            Title = "interductionSeven",
                            UserID = 7
                        },
                        new
                        {
                            PostID = 11,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(1021),
                            State = 0,
                            Title = "interductionEight",
                            UserID = 8
                        },
                        new
                        {
                            PostID = 12,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(1026),
                            State = 0,
                            Title = "interductionNiNe",
                            UserID = 9
                        },
                        new
                        {
                            PostID = 13,
                            Content = "English texts for beginners to practice reading",
                            DatedPost = new DateTime(2024, 11, 6, 0, 3, 39, 622, DateTimeKind.Local).AddTicks(1031),
                            State = 0,
                            Title = "interductionNine",
                            UserID = 9
                        });
                });

            modelBuilder.Entity("DAL.Model.UesrProfile", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FristName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("uesrProfiles");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            DateOfBirth = new DateTime(1999, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmedhasseb310@gmail.com",
                            FristName = "Ahmed",
                            LastName = "Mohamed",
                            State = 0
                        },
                        new
                        {
                            UserID = 2,
                            DateOfBirth = new DateTime(1999, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "MohamedAlaa12@gmail.com",
                            FristName = "Mohamed",
                            LastName = "Alaa",
                            State = 0
                        },
                        new
                        {
                            UserID = 3,
                            DateOfBirth = new DateTime(1999, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "AliMohamed@gmail.com",
                            FristName = "Ali",
                            LastName = "Ahmed",
                            State = 0
                        },
                        new
                        {
                            UserID = 4,
                            DateOfBirth = new DateTime(1999, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "YaserAli10@gmail.com",
                            FristName = "Yasser",
                            LastName = "Ali",
                            State = 0
                        },
                        new
                        {
                            UserID = 5,
                            DateOfBirth = new DateTime(2000, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ManarMohamed311@gmail.com",
                            FristName = "Manar",
                            LastName = "Mohamed",
                            State = 0
                        },
                        new
                        {
                            UserID = 6,
                            DateOfBirth = new DateTime(2001, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "saraAhmedOficial@gmail.com",
                            FristName = "Sara",
                            LastName = "Ahmed",
                            State = 0
                        },
                        new
                        {
                            UserID = 7,
                            DateOfBirth = new DateTime(1995, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "HemaHesham40@gmail.com",
                            FristName = "Ibrahim",
                            LastName = "Hesham",
                            State = 0
                        },
                        new
                        {
                            UserID = 8,
                            DateOfBirth = new DateTime(1992, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "esraaMostafa55@gmail.com",
                            FristName = "Esraa",
                            LastName = "Mostafa",
                            State = 0
                        },
                        new
                        {
                            UserID = 9,
                            DateOfBirth = new DateTime(2005, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ZeyadAdel665@gmail.com",
                            FristName = "Zeyad",
                            LastName = "Adel",
                            State = 0
                        });
                });

            modelBuilder.Entity("DAL.Model.Post", b =>
                {
                    b.HasOne("DAL.Model.UesrProfile", "UesrProfiles")
                        .WithMany("Posts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UesrProfiles");
                });

            modelBuilder.Entity("DAL.Model.UesrProfile", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
